### ISSUE TITLE
AttributeError: 'bool' object has no attribute '__module__'. Did you mean: '__mod__'?

### ISSUE THREAD

**Issue by sp1cae** [Tencent/Hunyuan3D-1#40]
Traceback (most recent call last):
  File "/Hunyuan3D-1/main.py", line 114, in <module>
    text_to_image_model = Text2Image(
  File "/Hunyuan3D-1/infer/text_to_image.py", line 41, in __init__
    self.pipe = AutoPipelineForText2Image.from_pretrained(
  File "/Hunyuan3D-1/venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/Hunyuan3D-1/venv/lib/python3.10/site-packages/diffusers/pipelines/auto_pipeline.py", line 382, in from_pretrained
    return text_2_image_cls.from_pretrained(pretrained_model_or_path, **kwargs)
  File "/Hunyuan3D-1/venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/Hunyuan3D-1/venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 966, in from_pretrained
    model = pipeline_class(**init_kwargs)
  File "/Hunyuan3D-1/venv/lib/python3.10/site-packages/diffusers/pipelines/pag/pipeline_pag_hunyuandit.py", line 208, in __init__
    self.register_modules(
  File "/Hunyuan3D-1/venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 159, in register_modules
    library, class_name = _fetch_class_library_tuple(module)
  File "/Hunyuan3D-1/venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_loading_utils.py", line 731, in _fetch_class_library_tuple
    library = not_compiled_module.__module__.split(".")[0]
AttributeError: 'bool' object has no attribute '__module__'. Did you mean: '__mod__'?

**Comment by sp1cae** [comment]
尝试了0.30 0.31 0.25 0.28 0.29的diffusers

**Comment by jiarenyf** [comment]
0.20.0试试呢
