### ISSUE TITLE
RuntimeError: Not compiled with GPU support

### ISSUE THREAD

**Issue by sp1cae** [Tencent/Hunyuan3D-1#42]
pytorch3d
Traceback (most recent call last):
  File "/Hunyuan3D-1/main.py", line 161, in <module>
    gif_renderer(
  File "/Hunyuan3D-1/infer/utils.py", line 51, in wrapper
    result = func(*args, **kwargs)
  File "/Hunyuan3D-1/infer/gif_render.py", line 50, in __call__
    render(
  File "/Hunyuan3D-1/svrm/ldm/vis_util.py", line 77, in render
    images = renderer(meshes)
  File "/opt/conda/envs/hunyuan3d-1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/hunyuan3d-1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/hunyuan3d-1/lib/python3.10/site-packages/pytorch3d/renderer/mesh/renderer.py", line 63, in forward
    fragments = self.rasterizer(meshes_world, **kwargs)
  File "/opt/conda/envs/hunyuan3d-1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/hunyuan3d-1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/hunyuan3d-1/lib/python3.10/site-packages/pytorch3d/renderer/mesh/rasterizer.py", line 254, in forward
    pix_to_face, zbuf, bary_coords, dists = rasterize_meshes(
  File "/opt/conda/envs/hunyuan3d-1/lib/python3.10/site-packages/pytorch3d/renderer/mesh/rasterize_meshes.py", line 225, in rasterize_meshes
    pix_to_face, zbuf, barycentric_coords, dists = _RasterizeFaceVerts.apply(
  File "/opt/conda/envs/hunyuan3d-1/lib/python3.10/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/opt/conda/envs/hunyuan3d-1/lib/python3.10/site-packages/pytorch3d/renderer/mesh/rasterize_meshes.py", line 298, in forward
    pix_to_face, zbuf, barycentric_coords, dists = _C.rasterize_meshes(
RuntimeError: Not compiled with GPU support

**Comment by jtydhr88** [comment]
I think this issue not relating to this repo, it is casued by pytorch3d

**Comment by HuiwenShi** [comment]
I previously encountered a similar error after upgrading the CUDA version following the installation of PyTorch3D. 
I recommend checking your CUDA version and then running the following command again:
```bash
pip3 install git+https://github.com/facebookresearch/pytorch3d@stable
```
