### ISSUE TITLE
for windows user

### ISSUE THREAD

**Issue by jtydhr88** [Tencent/Hunyuan3D-1#9]
Hi,
I just run it on Windows 10, here is my step.
Env:
Windows 10
3090

Prerequisites:
1. conda
2. you also need to install c++ build tools from [here](https://visualstudio.microsoft.com/visual-cpp-build-tools/) 
![img_1](https://github.com/user-attachments/assets/0229c5e6-af4d-45f8-988a-34f513bef906)

Steps:
1. conda create -n hunyuan3d-py39 python=3.9
2. conda activate hunyuan3d-py39
3. pip install torch==2.2.0 torchvision==0.17.0 --index-url https://download.pytorch.org/whl/cu118
4. pip install diffusers transformers
5. pip install rembg tqdm omegaconf matplotlib opencv-python imageio jaxtyping einops
6. pip install SentencePiece accelerate trimesh PyMCubes xatlas libigl
7. pip install git+https://github.com/facebookresearch/pytorch3d
8. pip install git+https://github.com/NVlabs/nvdiffrast
9. pip install open3d
10. pip install Ninja
11. pip install gradio
12. git clone https://github.com/Tencent/Hunyuan3D-1
13. cd Hunyuan3D-1
14. pip install "huggingface_hub[cli]"
15. create folder ./weights and ./weights/hunyuanDiT
16. huggingface-cli download tencent/Hunyuan3D-1 --local-dir ./weights
17. huggingface-cli download Tencent-Hunyuan/HunyuanDiT-v1.1-Diffusers-Distilled --local-dir ./weights/hunyuanDiT
18. go to app.py and change 0.0.0.0 to 127.0.0.1 on line 52
19. go to demos/example_list.txt and remove the first 3 lines of Chinese prompts.
20. python app.py

quick test
![image](https://github.com/user-attachments/assets/70a8c80b-cba2-447d-a94d-63438d2c4ebb)
![image](https://github.com/user-attachments/assets/2d6a1370-acb6-4c03-8cd5-16849514b5f3)

good luck!

**Comment by h3clikejava** [comment]
3090多少显存也能跑？

**Comment by jtydhr88** [comment]
可以，就是慢点

**Comment by jtydhr88** [comment]
Update for python 3.11 and cuda 12.4, this repo also works well with them as tested.
Prerequisites:

1. conda
2. cuda 12.4
3. you still need to install c++ build tools from [here](https://visualstudio.microsoft.com/visual-cpp-build-tools/)

Different Steps:
1. conda create -n hunyuan3d-py311 python=3.11
2. conda activate hunyuan3d-py311
3. pip install torch torchvision xformers --index-url https://download.pytorch.org/whl/cu121
4. (optional) you can download trition whl https://huggingface.co/madbuda/triton-windows-builds, as I am using python 3.11, so I will download 3.11 version
5. (optional) pip install triton-2.1.0-cp311-cp311-win_amd64.whl

other steps are as same as above.

**Comment by wWzZb** [comment]
![image](https://github.com/user-attachments/assets/b529a951-0bda-4ded-ae87-60658c1267fa)
安装SentencePiece accelerate trimesh PyMCubes xatlas libigl等库时报错，可以使用国内镜像，
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple SentencePiece accelerate trimesh PyMCubes xatlas libigl，
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple git+https://github.com/facebookresearch/pytorch3d

**Comment by jrc48** [comment]
i'm stuck at installing pytorch3d, can anyone help?

**Comment by jtydhr88** [comment]
> i'm stuck at installing pytorch3d, can anyone help?

please post your error

**Comment by jrc48** [comment]
Collecting git+https://github.com/facebookresearch/pytorch3d
Cloning https://github.com/facebookresearch/pytorch3d to c:\users\jing\appdata\local\temp\pip-req-build-ezsxm3_q
Resolved https://github.com/facebookresearch/pytorch3d to commit 81d82980bc82fd605f27cca87f89ba08af94db3d
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'done'
Collecting iopath (from pytorch3d==0.7.8)
Using cached iopath-0.1.10-py3-none-any.whl
Requirement already satisfied: tqdm in c:\programdata\anaconda3\envs\hunyuan3d-py39\lib\site-packages (from iopath->pytorch3d==0.7.8) (4.67.0)
Requirement already satisfied: typing-extensions in c:\programdata\anaconda3\envs\hunyuan3d-py39\lib\site-packages (from iopath->pytorch3d==0.7.8) (4.9.0)
Collecting portalocker (from iopath->pytorch3d==0.7.8)
Using cached portalocker-2.10.1-py3-none-any.whl.metadata (8.5 kB)
Collecting pywin32>=226 (from portalocker->iopath->pytorch3d==0.7.8)
Using cached pywin32-308-cp39-cp39-win_amd64.whl.metadata (8.3 kB)
Requirement already satisfied: colorama in c:\programdata\anaconda3\envs\hunyuan3d-py39\lib\site-packages (from tqdm->iopath->pytorch3d==0.7.8) (0.4.6)
Using cached portalocker-2.10.1-py3-none-any.whl (18 kB)
Using cached pywin32-308-cp39-cp39-win_amd64.whl (6.6 MB)
Building wheels for collected packages: pytorch3d
Building wheel for pytorch3d (setup.py): started
Building wheel for pytorch3d (setup.py): finished with status 'error'
Running setup.py clean for pytorch3d
Failed to build pytorch3d

**Comment by HuiwenShi** [comment]
Try git+https://github.com/facebookresearch/pytorch3d@stable

**Comment by SoftologyPro** [comment]
I built a WHL for Pytorch3D to help install problems
https://huggingface.co/datasets/Softology-Pro/VoC/resolve/main/pytorch3d-0.7.8-cp310-cp310-win_amd64.whl

**Comment by jrc48** [comment]
> * pip install torch torchvision xformers --index-url https://download.pytorch.org/whl/cu121

still the same

**Comment by mateobadillo** [comment]
Im also having issues with Pytorch3D, even though I have torch installed I get this error

(hunyuan3d-py311) C:\Users\mateo\Hunyuan3D-1>pip install git+https://github.com/facebookresearch/pytorch3d@stable
Collecting git+https://github.com/facebookresearch/pytorch3d@stable
  Cloning https://github.com/facebookresearch/pytorch3d (to revision stable) to c:\users\mateo\appdata\local\temp\pip-req-build-yosm9hap
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/pytorch3d 'C:\Users\mateo\AppData\Local\Temp\pip-req-build-yosm9hap'
  Running command git checkout -q 75ebeeaea0908c5527e7b1e305fbc7681382db47
  Resolved https://github.com/facebookresearch/pytorch3d to commit 75ebeeaea0908c5527e7b1e305fbc7681382db47
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\mateo\AppData\Local\Temp\pip-req-build-yosm9hap\setup.py", line 15, in <module>
          import torch
        File "C:\Users\mateo\anaconda3\envs\hunyuan3d-py311\Lib\site-packages\torch\__init__.py", line 148, in <module>
          raise err
      OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\mateo\anaconda3\envs\hunyuan3d-py311\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.


![Image](https://github.com/user-attachments/assets/8cdecab6-bf77-4e9f-a8c8-f1c941aeff8e)
